# Generated by Django 5.0.1 on 2024-08-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="following",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="followers", to="media.profile"
            ),
        ),
    ]
