# Generated by Django 5.0.1 on 2024-09-03 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["user_id"], "verbose_name_plural": "profiles"},
        ),
    ]
