# Generated by Django 5.0.1 on 2024-08-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0003_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to="media.profile"
            ),
        ),
    ]
