# Generated by Django 5.0.1 on 2024-08-25 15:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0004_alter_profile_following"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="username",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=120
            ),
            preserve_default=False,
        ),
    ]
