# Generated by Django 5.0.1 on 2024-08-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0005_profile_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="username",
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
